### ISSUE TITLE
Новый игровой режим

### ISSUE THREAD

**Issue by hunter1486** [romeoordos/tanktastic#111]
Предлагаю по достижении топового танка (70+ ибэ) открыть доступ до нового игрового режима(с фракциями) когда человек покупает допустим армату то ему предоставляется выбор одной из трёх фракций. После выбора раз в неделю будут игры фракций в которых он может принимать участие. И получать призы, и в зависимости от фракции будет какой-либо бонус (+10% к опыту или +10% к серебру, скидки на технику и т.д.) собственно как будут балансится команды. Будет сообщение о начале фракционных игр. Нажав на кнопку в бой игрок попадает в лобби. Исходя из этого будут распределяться команды и количество комнат. И по окончанию приёма заявок(спустя 5 минут) всех будет разбрасывать (естественно в свою фракцию)

**Comment by hunter1486** [comment]
И сделать ограничение по Артам в количестве двух штук) перед боем игрок выбирает технику допустимого уровня и тот кто первый возьмет ТОС тот и будет на нем играть.

**Comment by romeoordos** [comment]
Пока игра имеет низкий спрос, любой вариант ограничения к режимам/картам по уровням не имеет смысла. Как и клановые бои.
