### ISSUE TITLE
Возможность выбора стартовой техники

### ISSUE THREAD

**Issue by DerFieldmarshal** [romeoordos/tanktastic#112]
Можно дать возможность выбирать стартовую технику из нескольких вариантов (Т-54, Т92, Тип-59, например)

**Comment by DenisTW** [comment]
После реализации такой незначительной фишки поступит предложение давать не один а сразу три танка из каждой ветки как в других играх, потому что аппетиты растут, а подумать и предложить конечный вариант не получается)). 
Имхо,результат не будет стоить затрат. Перед тем как делать осознанный выбор, нужно знать с чем придется столкнуться и чего желать на будущее. Стартовые танки стоят копейки, Новичку золота дают при старте и наборе первых рангов, что хватит на все стартовые. При этом,если у него на старте будет не тот танк что ему хочется,есть вероятность что неудачи первых боёв не заставят удалить игру сразу,а он как минимум захочет приобрести то что ему хотелось.

**Comment by romeoordos** [comment]
получение стартовой техники в зависимости от страны игрока было фишкой игры с самого начала. Никаких других вариантов пока не будет.
