### ISSUE TITLE
Краткая историческая справка

### ISSUE THREAD

**Issue by DerFieldmarshal** [romeoordos/tanktastic#117]
К каждому танку можно добавить короткую справку
(если заинтресует, найду инфу по всей технике)

**Comment by Drestdave** [comment]
What do you mean?

**Comment by DerFieldmarshal** [comment]
To add historical information about game vehicles, real facts about it

**Comment by DenisTW** [comment]
Это увеличит вес приложения набив его одноразовой информацией, следом за этим поступит закономерное предложение добавить справку по игровой технике. В итоге мы получим усложнение интерфейса, лишний вес и очень сомнительную надобность,по крайней мере  в варианте с историей.
Все же, это не википедия.

**Comment by romeoordos** [comment]
Согласен с Денисом. Подобная информация не имеет отношения к игре, и не несёт никакого практического смысла.
