### ISSUE TITLE
Вылеты из игры на iOS

### ISSUE THREAD

**Issue by DerFieldmarshal** [romeoordos/tanktastic#119]
На iOS при
- смахивании верхней и нижней шторки
- использования кнопки «домой»
- предупреждениях и оповещениях системы (количество заряда батареи, например)

вылетает игра, и затем снова подключается. Бой, разумеется, тоже вылетает. 
Большая проблема, особенно на волне борьбы с логгингом

**Comment by romeoordos** [comment]
Проблема в принудительном отключении от сети при переходе игры в режим паузы. Зачем так сделано не знаю. Убрал.
