### ISSUE TITLE
Смена танка в бою

### ISSUE THREAD

**Issue by Palantid** [romeoordos/tanktastic#133]
Добавить возможность после смерти сменить танк не выходя из рума.

**Comment by DenisTW** [comment]
У меня встречное предложение, вернуть аннуляцию доходов  за смену танка, как это было раньше. Мотивация проста - задолбали ракообразные скакуны сигающие из боя при первых же плюхах и бегущие за имбой. Приходишь поиграть на танках шестидесятых и через две минуты уже пол рума на танках восьмидесятых. За железную отмазку логеров  вообще молчу- "я просто сменить танк, я не логер". Смена танка во время боя приведет к бесконечной карусели техники, усложнит очень многое и добавит кучу проблем. 
Я категорически против горячей смены техники и обеими руками за 30-60 секундный таймаут на возвращение в бой из которого вышел/вылетел. Ибо нефиг, пришел-играй,закончился бой-иди на все четыре стороны и играй на чем хочешь.

**Comment by Palantid** [comment]
Ну да, если рассматривать с этой стороны, то я тоже за такую систему. Просто идея о смене танков пришла в голову из-за предложения #69 про статистику. Типа чтобы ливерам засчитывался килл в стату за их постоянный уход, а у желающих сменить танк была возможность это сделать без ухудшения своей статистики.

Но если концепция про таймаут реализуема, то я тоже за обеими руками. Тогда можно будет ввести #69  K/D вместе с нанесенным уроном/полученным уроном в командные бои с цветовой индикацией и ливеры уже никак не смогут повлиять на улучшение этих показателей. 

Хотелось бы поднять эту тему про статистику. Потому что она реально годная. А все недочеты о ней, указанные Денисом, убираются добавлением такой статистики только в командные бои и добавлением таймаута для ливеров.

**Comment by DenisTW** [comment]
К/Д как и соотношение нанесенного к полученному урону  у нас не имеет никакого смысла, оно совершенно бестолковое и не отражающее действительность. Оно не покажет ничего, объективность нулевая. Я неоднократно замечал что затащив бой по фрагам и получив немалый килл ассист можно нанести урона меньше чем получить, особенно играя на тяжелой броне. В игре с респаунами и хилками эта инфа будет слишком расплывчата и непонятна для 99% игроков. Что считать хорошим соотношением для тащера в таком случае? Ведь эти бои я тащу по К/Д в первую очередь, но мои соперники получают лучшее соотношение по дамагу, потому что я успеваю хилиться и респать чаще чем ухожу на респ сам.

**Comment by Palantid** [comment]
Как раз таки можно определить более лучшего игрока по этим показателям. Игроки, имеющие в статистике хорошее соотношение по урону умеют разумно размениваться и не уходить в респаун очень долго, это я замечал уже много раз. Тем самым они очень полезны для команды. Судя по тому, с какими статами сейчас вывозит самый пока что сильный клан другие кланы, хорошее соотношение для тащера на простых пабликах - это трочека. Да, такой статы будет очень сложно добиться и она будет у единиц, но надо ведь игрокам к чему-то стремиться.
  Еще есть предложения добавить такую статистику только для игры на танках самого высокого уровня, чтобы дать потом новичкам нормально откалиброваться. Потому что пока они будут качаться до топов, их стата в командных боях будет слабая и потом исправлять все это анриал.
 
И самое главное,  для чего может пригодиться в дальнейшем такое нововведение - это какие-нибудь ранговые командные сражения 3vs3 или 4vs4, где наградой будет золото в зависимости от ранга. Статистика поможет откалибровать игрока и если у него она очень хорошая, дать ему уже  высокий ранг, где он будет сразу же играть с игроками по его скиллу. За золото будут покупаться те самые боксы со шкурками (кстати, на новичках может и мало кто ездит в камо, а вот еще ветерана без дорогущего камка я еще не видел, так что уникальные шкурки в боксах будут очень актуальны для ребят, купивших топ танк)  и получится вот такой замкнутый круг, который надолго удержит игрока, купившего топовый танк, а у новичков и среднячков будет еще один стимул для выкачивания последних танков, чтобы опробовать всю эту интереснейшую систему со статой и ранговыми сражениями

**Comment by Palantid** [comment]
Как раз таки можно определить более лучшего игрока по этим показателям. Игроки, имеющие в статистике хорошее соотношение по урону умеют разумно размениваться и не уходить в респаун очень долго, это я замечал уже много раз. Тем самым они очень полезны для команды. Судя по тому, с какими статами сейчас вывозит самый пока что сильный клан другие кланы, хорошее соотношение для тащера на простых пабликах - это 2.0 Да, такой статы будет очень сложно добиться и она будет у единиц, но надо ведь игрокам к чему-то стремиться.
Еще есть предложения добавить такую статистику только для игры на танках самого высокого уровня, чтобы дать потом новичкам нормально откалиброваться. Потому что пока они будут качаться до топов, их стата в командных боях будет слабая и потом исправлять все это анриал.

И самое главное, для чего может пригодиться в дальнейшем такое нововведение - это какие-нибудь ранговые командные сражения 3vs3 или 4vs4, где наградой будет золото в зависимости от ранга. Статистика поможет откалибровать игрока и если у него она очень хорошая, дать ему уже высокий ранг, где он будет сразу же играть с игроками по его скиллу. За золото будут покупаться те самые боксы со шкурками (кстати, на новичках может и мало кто ездит в камо, а вот еще ветерана без дорогущего камка я еще не видел, так что уникальные шкурки в боксах будут очень актуальны для ребят, купивших топ танк) и получится вот такой замкнутый круг, который надолго удержит игрока, купившего топовый танк, а у новичков и среднячков будет еще один стимул для выкачивания последних танков, чтобы опробовать всю эту интереснейшую систему со статой и ранговыми сражениями

> К/Д как и соотношение нанесенного к полученному урону у нас не имеет никакого смысла, оно совершенно бестолковое и не отражающее действительность. Оно не покажет ничего, объективность нулевая. Я неоднократно замечал что затащив бой по фрагам и получив немалый килл ассист можно нанести урона меньше чем получить, особенно играя на тяжелой броне. В игре с респаунами и хилками эта инфа будет слишком расплывчата и непонятна для 99% игроков. Что считать хорошим соотношением для тащера в таком случае? Ведь эти бои я тащу по К/Д в первую очередь, но мои соперники получают лучшее соотношение по дамагу, потому что я успеваю хилиться и респать чаще чем ухожу на респ сам.

**Comment by Palantid** [comment]
Как раз таки можно определить более лучшего игрока по этим показателям. Игроки, имеющие в статистике хорошее соотношение по урону умеют разумно размениваться и не уходить в респаун очень долго, это я замечал уже много раз. Тем самым они очень полезны для команды. Судя по тому, с какими статами сейчас вывозит самый пока что сильный клан другие кланы, хорошее соотношение для тащера на простых пабликах - это 2.0 Да, такой статы будет очень сложно добиться и она будет у единиц, но надо ведь игрокам к чему-то стремиться.
Еще есть предложения добавить такую статистику только для игры на танках самого высокого уровня, чтобы дать потом новичкам нормально откалиброваться. Потому что пока они будут качаться до топов, их стата в командных боях будет слабая и потом исправлять все это анриал.

И самое главное, для чего может пригодиться в дальнейшем такое нововведение - это какие-нибудь ранговые командные сражения 3vs3 или 4vs4, где наградой будет золото в зависимости от ранга. Статистика поможет откалибровать игрока и если у него она очень хорошая, дать ему уже высокий ранг, где он будет сразу же играть с игроками по его скиллу. За золото будут покупаться те самые боксы со шкурками (кстати, на новичках может и мало кто ездит в камо, а вот еще ветерана без дорогущего камка я еще не видел, так что уникальные шкурки в боксах будут очень актуальны для ребят, купивших топ танк) и получится вот такой замкнутый круг, который надолго удержит игрока, купившего топовый танк, а у новичков и среднячков будет еще один стимул для выкачивания последних танков, чтобы опробовать всю эту интереснейшую систему со статой и ранговыми сражениями
