### ISSUE TITLE
Отсутствие текстур для вертолетов / No Textures on the Helicopter

### ISSUE THREAD

**Issue by Jbdd-LZ** [romeoordos/tanktastic#145]
Эта проблема никогда не была замечена из предыдущих обновлений, не раздражает ошибка, но она нуждается в исправлении.

Изображение прилагается ниже:

![image](https://user-images.githubusercontent.com/47507382/52540257-b8f45080-2d55-11e9-8a66-d96c8d563e36.png)

**Comment by romeoordos** [comment]
fixed
