### ISSUE TITLE
Adjust screen resolution for Xiaomi Pocophone F1

### ISSUE THREAD

**Issue by Error-Forbidden** [romeoordos/tanktastic#4]
Adjust the screen resolution for _[Xiaomi Pocophone F1](https://www.gsmarena.com/xiaomi_pocophone_f1-9293.php)_ devices.

![bilde](https://user-images.githubusercontent.com/23483786/51043931-2f1f5f00-15c0-11e9-985e-004e749cc205.png)

**Comment by romeoordos** [comment]
Seems like engine issue. May be fixed with engine upgrade.

**Comment by basmal121** [comment]
This, as well as **all phones/tablets with rounded screen corners.** these have same issue.

**Comment by Jacobvm1234** [comment]
Samsung Galaxy S8 also has that, but its ok

**Comment by Udaril-i** [comment]
Xiaomi redmi note 5 полоса только с одной стороны

**Comment by romeoordos** [comment]
done
