### ISSUE TITLE
Новые игровые режимы / New game modes

### ISSUE THREAD

**Issue by DerFieldmarshal** [romeoordos/tanktastic#44]
Можно бы было ввести новые игровые режимы, возможно даже популярный ныне баттл рояль (большая карта типа пустыни, с разбросанными улучшениями характеристик танка в виде коробок), либо бой на 3 команды, либо танковый биатлон с ограничениями по стрельбе и автоматическими штрафами конечного счета при нарушениях на трассе, или что-то типа того.

**Comment by DerFieldmarshal** [comment]
It would be possible to introduce new game modes, perhaps even the now-popular Battle Royale (large desert-type map, with scattered improvements of tank characteristics in the form of boxes), or a battle for 3 teams, or tank biathlon with shooting restrictions and automatic fines of the final score for violations on the track, or something like that.

**Comment by Jacobvm1234** [comment]
I'm not sure how a battle royale mode would work out in tanktastic. I don't think we should focus on the current mainstream games

**Comment by romeoordos** [comment]
Duplicate of #9 
Duplicate of #10 
Duplicate of #11 
Duplicate of #12
