### ISSUE TITLE
Альтернативный режим прицеливания артиллерии

### ISSUE THREAD

**Issue by DerFieldmarshal** [romeoordos/tanktastic#56]
Предлагаю ввести режим артиллерийской стрельбы, каким он был ранее, как альтернативу нынешнему прицелу. Это могло бы добавить реализма артиллерийской стрельбе, так как реальные САУ обладают возможностью стрельбы прямой наводкой и сделает артиллерийские системы в игре не столь беззащитными при танковой атаке.

**Comment by DerFieldmarshal** [comment]
https://youtu.be/aXLACEzp7ok
прицел такой, как в этом ролике

**Comment by DenisTW** [comment]
Менять механику смысла нет, это ненужное усложнение, более простой вариант  того что ты хочешь давно внесен на рассмотрение, но далеко не факт что он будет принят. Механика и визуализация арт прицела относится в некоторой степени к балансу.
