### ISSUE TITLE
Карты (для новичков)

### ISSUE THREAD

**Issue by hunter1486** [romeoordos/tanktastic#75]
Почему бы демку и дикий запад не сделать доступными до 15 ранга, после которого начнутся открывать вся другие карты? Это должно помочь новичкам в их изучении

**Comment by romeoordos** [comment]
При таком низком онлайне это лишнее ограничение.

**Comment by hunter1486** [comment]
> При таком низком онлайне это лишнее ограничение.

так на низком ибэ же все по картам разбегаются и все по 2-3 человека сидят. а так будут только на двух )))
