### ISSUE TITLE
Add more social media's.

### ISSUE THREAD

**Issue by Jacobvm1234** [romeoordos/tanktastic#88]
Add more social media's (Discord etc)

Image: https://cdn.discordapp.com/attachments/533257455745105920/534454456193122304/20190114_202957.jpg

**Comment by romeoordos** [comment]
Each social media requires implementing and maintaining native plugins for both mobile platforms. We use the most popular ones. No other will be implemented.

**Comment by Jacobvm1234** [comment]
In the tt community, discord is probably the most popular.
