### ISSUE TITLE
In-game screen recorder

### ISSUE THREAD

**Issue by Jacobvm1234** [romeoordos/tanktastic#96]
If possible, add a screen recorder that can record at least 720p (depending upon device specifications). Players are given more options to create video content without recording external sound.

**Comment by romeoordos** [comment]
Use software from AppStore/Google Play for that purpose.

**Comment by Jacobvm1234** [comment]
> Use software from AppStore/Google Play for that purpose.

The software from Google Play won't allow us to record internal sound only. It has to record external sound as well, this is not an option to turn off. 
If I'm not mistaken, this was a limitation Google made a few years ago.
