### ISSUE TITLE
2-auth on your account

### ISSUE THREAD

**Issue by Jacobvm1234** [romeoordos/tanktastic#98]
Add the option to have 2-auth on your tt account so that a potential "hacker" gets this when trying to access other players account illegally.

By the time I'm writing this it has 9 upvotes and 0 downvotes on the discord server.

Image: 
https://cdn.discordapp.com/attachments/533257455745105920/534475529563275264/Screenshot_2019-01-14-21-53-38.png

**Comment by romeoordos** [comment]
You should protect your account on your own. Game will never allow you to login one account from multiple devices at the same time.
